# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=40)),
                ('user', models.ManyToManyField(blank=True, null=True, to='one.IpUser')),
            ],
        ),
    ]
