# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceone',
            name='device',
            field=models.OneToOneField(blank=True, help_text='help test', null=True, on_delete=django.db.models.deletion.CASCADE, to='one.Device'),
        ),
    ]
