# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_iprole'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permname', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='iprole',
            name='user',
            field=models.ManyToManyField(blank=True, to='one.IpUser'),
        ),
        migrations.AddField(
            model_name='ippermission',
            name='roleperm',
            field=models.ManyToManyField(to='one.IpRole'),
        ),
    ]
