# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-23 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0004_device_devicegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='devicegroup',
            name='groupname',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
